# Generated by Django 4.2.5 on 2023-10-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_course_coursetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(default='A', help_text='Course section (e.g., A, B, C)', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text="Student's enrolled section for the course", max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.student')),
            ],
            options={
                'db_table': 'student_course_mapping',
                'unique_together': {('student', 'course', 'section')},
            },
        ),
        migrations.CreateModel(
            name='FacultyCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text="Faculty's assigned section for the course", max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty')),
            ],
            options={
                'db_table': 'faculty_course_mapping',
                'unique_together': {('faculty', 'course', 'section')},
            },
        ),
    ]
