# Generated by Django 4.2.5 on 2023-11-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_course_section_studentcoursemapping_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCourseMapping',
        ),
    ]
