# Generated by Django 4.2.5 on 2023-11-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_faculty_contact_alter_faculty_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='year',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
