# Generated by Django 4.2.5 on 2023-11-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_facultycoursemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseMapping',
            fields=[
                ('mappingid', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.student')),
            ],
            options={
                'db_table': 'studentcoursemapping_table',
            },
        ),
    ]
