# Generated by Django 4.2.5 on 2023-11-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultystudentmapping',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
